### ISSUE TITLE
chown: cannot access '/meterian-cli.jar': No such file or directory

### ISSUE THREAD

**Issue by matteobaccan** [MeterianHQ/meterian-github-action#6]
Hi

I use a very simple workflow

<pre>
name: vulnerability scan workflow

on: push

jobs:
    meterian_scan:
        name: Meterian client scan
        runs-on: ubuntu-latest
        steps: 
          - name: Checkout
            uses: actions/checkout@v2
          - name: Scan project with the Meterian client
            uses: MeterianHQ/meterian-github-action@v1.0.5
            env:
                METERIAN_API_TOKEN: ${{ secrets.METERIAN_API_TOKEN }}
            with:
                cli_args: "" #[ Meterian CLI Options ]
</pre>

but when Github execute it, I have this error:

<pre>
Run MeterianHQ/meterian-github-action@v1.0.5
  with:
  env:
    METERIAN_API_TOKEN: ***
/usr/bin/docker run --name b3ac674135a87badc490bb7537d8d997c1e63_fc1aac --label 3b3ac6 --workdir /github/workspace --rm -e METERIAN_API_TOKEN -e INPUT_CLI_ARGS -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/html2pop3/html2pop3":"/github/workspace" 3b3ac6:74135a87badc490bb7537d8d997c1e63  ""

chown: cannot access '/meterian-cli.jar': No such file or directory
</pre>

Why I have this error?

all the best
matteo baccan

**Comment by bbossola** [comment]
The issue is confirmed.

**Comment by bbossola** [comment]
The issue is fixed. Thanks for letting  us know :)
